config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/access_level.rb
class AccessLevel < ApplicationRecord
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, :date, :venue, presence: true
  validates :description, presence: true, length: {minimum: 20}

  scope :upcoming, -> { where("Date >= ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :access_level
  has_many :events

  before_validation :set_access_level

  validates :username, :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  validates :password_confirmation, :access_level_id, presence: true

  private

  def set_access_level
    privileged ||= AccessLevel.find_by(name: 'privileged')
    ordinary ||= AccessLevel.find_by(name: 'ordinary')

    if email.eql?('buna@buna.com')
      self.access_level_id = privileged.id
    else
      self.access_level_id = ordinary.id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :buna?

  private

  def authenticate_user
    unless logged_in?
      redirect_to root_path, alert: 'You need to login first!'
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    true if current_user
  end

  def buna?
    # poignant guide baby!
    true if current_user.access_level.name == 'privileged' if current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, except: :index

  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def update
    @event = Event.find(params[:id])
    will_attend = params[:commit] == 'Ofcourse, I will Attend!'

    @event.update!(attendance: will_attend)
    redirect_to event_path(@event)
  end

  def create
    user = User.find(session[:user_id])
    @event = user.events.build(form_params)

    if @event.save
      redirect_to root_path, notice: 'Event successfully created!'
    else
      render :new, status: :internal_server_error
    end
  end

  private

  def form_params
    params.require(:event).permit(:title, :description, :date, :venue)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "#{current_user.username.capitalize}, You are successfully logged in"
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new, status: :internal_server_error
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully, logged out!'
  end

  private 

  def form_params 
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      redirect_to root_url, notice: 'User successfully created'
    else
      render :new, status: :internal_server_error
    end
  end

  private

  def create_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/index.html.erb
<main class="container">
  <h1>All Events</h1>
  <% if @events.empty? %>
    <p>No events to show</p>
  <% else %>
    <ul>
      <% @events.each do |e| %>
        <li class='event-card'>
          <%= link_to e, class: 'docile-link' do %>
            <% if e.attendance %>
              <p class='status-box attending'>attending</p>
            <% else %>
              <p class='status-box not-attending'>not attending</p>
            <% end %>
            <h3> <%= e.title %> </h3>
            <p><%= e.description.slice(0..60) + '...' %></p>
            <p class='date'>event on: <%= e.date %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</main>

app/views/events/new.html.erb
<main class="container">
  <% unless @event.errors.empty? %>
    <section class='error-message sidebar'>
      <h2>Error Messages</h2>
      <ul>
        <% @event.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <section>
    <h1>Create Event</h1>

    <%= form_with model: @event do |f| %>
      <div>
        <%= f.label :title, class: :required %><br>
        <%= f.text_field :title, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :description, class: :required %><br>
        <%= f.text_area :description, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :date, 'Event date', class: :required %><br>
        <%= f.date_field :date, min: Date.tomorrow, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :venue, class: :required %><br>
        <%= f.text_field :venue, 'aria-required': true %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
  </section>
</main>

app/views/events/show.html.erb
<main class="container">
  <section class='show-event-card'>
    <h1><%= @event.title %></h1>
    <p>description: <%= @event.description %></p>
    <p>created by: <%= @event.user.username %></p>
    <p>event date: <%= @event.date %></p>
    <p>venue: <%= @event.venue %></p>
    <% if @event.attendance %>
      <p class='happy-message'>Mamu loves you so much!</p>
    <% else %>
      <p class='sad-message'>You are a great disappointment. I regret sending you an Iphone.</p>
    <% end %>
  </section>

  <% if buna? %>
    <section class='attendance-form-wrapper'>
      <h2>Will Buna attend?</h2>

      <%= form_with model: @event do |f| %>
        <%= f.submit 'Ofcourse, I will Attend!', class: 'big-border-on-focus' %>
        <%= f.submit 'Sorry, mamu does not love you enough', class: 'big-border-on-focus' %>
      <% end %>
    </section>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buna, Will You Attend?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash[:notice] %>
      <p class='flash notice'><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class='flash alert'><%= flash[:alert] %></p>
    <% end %>

    <nav>
      <%= link_to 'Buna, will you attend?', root_path, class: :logo %>
      <ul>
        <% if buna? %>
          <li><%= link_to :logout, logout_path %></li>
        <% elsif logged_in? %>
          <li><%= link_to 'Create Event', new_event_path %></li>
          <li><%= link_to :logout, logout_path %></li>
        <% else %>
          <li><%= link_to :Signup, signup_path %></li>
          <li><%= link_to :Login, login_path %></li>
        <% end %>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<main class="container">
  <% unless @user.errors.empty? %>
    <section class='error-message sidebar'>
      <h2>Error Messages</h2>
      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <section>
    <h1>Sign Up</h1>
    
    <%= form_with model: @user do |f| %>
      <div>
        <%= f.label :username, class: :required %><br>
        <%= f.text_field :username, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :email, class: :required %><br>
        <%= f.email_field :email, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :password, class: :required %><br>
        <%= f.password_field :password, 'aria-required': true %>
      </div>
      <div>
        <%= f.label :password_confirmation, class: :required %><br>
        <%= f.password_field :password_confirmation, 'aria-required': true %>
      </div>
      <div>
        <%= f.submit 'Sign Up' %>
      </div>
    <% end %>
  </section>
</main>